# Full configuration reference available at:
# https://damienharper.github.io/auditor-docs/docs/auditor-bundle/configuration/reference.html
dh_auditor:
    enabled: true
    providers:
        doctrine:
            table_prefix: null
            table_suffix: '_audit'
            ignored_columns:
                - createdAt
                - updatedAt
            entities:
                ProjetNormandie\UserBundle\Entity\User:
                    ignored_columns:
                        - password
                        - lastLogin
                        - confirmationToken
                        - nbConnexion
                        - extraData
                        - avatar
                VideoGamesRecords\CoreBundle\Entity\Game:
                    ignored_columns:
                        - nbChart
                        - nbPost
                        - nbPlayer
                        - nbVideo
                        - nbTeam
                        - forum
                        - lastUpdate
                        - lastScore
                VideoGamesRecords\CoreBundle\Entity\Platform:
                VideoGamesRecords\CoreBundle\Entity\Serie:
                    ignored_columns:
                        - nbChart
                        - nbGame
                VideoGamesRecords\CoreBundle\Entity\Rule:
                VideoGamesRecords\CoreBundle\Entity\ChartType:
                VideoGamesRecords\CoreBundle\Entity\PlayerChart:
                    ignored_columns:
                        - rank
                        - nbEqual
                        - pointChart
                        - pointPlatform
                        - isTopScore
                        - platform

            storage_services:
                - '@doctrine.orm.audit_entity_manager'
            auditing_services:
                - '@doctrine.orm.default_entity_manager'
            viewer: true
