framework:
    messenger:
        buses:
            messenger.bus.default:
                middleware:
                    - App\Messenger\Middleware\UniquenessMiddleware
                    - doctrine_transaction
                    - validation
                    - router_context
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'
            player_chart_rank:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: player_chart_rank
                retry_strategy:
                    max_retries: 0
            player_group_rank:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: player_group_rank
                retry_strategy:
                    max_retries: 0
            player_game_rank:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: player_game_rank
                retry_strategy:
                    max_retries: 0
            player_serie_rank:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: player_serie_rank
                retry_strategy:
                    max_retries: 0
            player_platform_rank:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: player_platform_rank
                retry_strategy:
                    max_retries: 0
            player_data:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: player_data
                retry_strategy:
                    max_retries: 0
            player_rank:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: player_rank
                retry_strategy:
                    max_retries: 0
            team_chart_rank:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: team_chart_rank
                retry_strategy:
                    max_retries: 0
            team_group_rank:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: team_group_rank
                retry_strategy:
                    max_retries: 0
            team_game_rank:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: team_game_rank
                retry_strategy:
                    max_retries: 0
            team_serie_rank:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: team_serie_rank
                retry_strategy:
                    max_retries: 0
            team_data:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: team_data
                retry_strategy:
                    max_retries: 0
            team_rank:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: team_rank
                retry_strategy:
                    max_retries: 0


        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            VideoGamesRecords\CoreBundle\Scheduler\Message\DailyRanking: async
            #Symfony\Component\Notifier\Message\ChatMessage: async
            #Symfony\Component\Notifier\Message\SmsMessage: async
            #Player Ranking
            VideoGamesRecords\CoreBundle\Message\Player\UpdatePlayerChartRank: player_chart_rank
            VideoGamesRecords\CoreBundle\Message\Player\UpdatePlayerGroupRank: player_group_rank
            VideoGamesRecords\CoreBundle\Message\Player\UpdatePlayerGameRank: player_game_rank
            VideoGamesRecords\CoreBundle\Message\Player\UpdatePlayerSerieRank: player_serie_rank
            VideoGamesRecords\CoreBundle\Message\Player\UpdatePlayerPlatformRank: player_platform_rank
            VideoGamesRecords\CoreBundle\Message\Player\UpdatePlayerData: player_data
            VideoGamesRecords\CoreBundle\Message\Player\UpdatePlayerRank: player_rank
            #Team Ranking
            VideoGamesRecords\CoreBundle\Message\Team\UpdateTeamChartRank: team_chart_rank
            VideoGamesRecords\CoreBundle\Message\Team\UpdateTeamGroupRank: team_group_rank
            VideoGamesRecords\CoreBundle\Message\Team\UpdateTeamGameRank: team_game_rank
            VideoGamesRecords\CoreBundle\Message\Team\UpdateTeamSerieRank: team_serie_rank
            VideoGamesRecords\CoreBundle\Message\Team\UpdateTeamData: team_data
            VideoGamesRecords\CoreBundle\Message\Team\UpdateTeamRank: team_rank

when@dev:
    framework:
        messenger:
            routing:
                Symfony\Component\Mailer\Messenger\SendEmailMessage: sync
                VideoGamesRecords\CoreBundle\Scheduler\Message\DailyRanking: sync
                #VideoGamesRecords\CoreBundle\Message\Player\UpdatePlayerChartRank: sync
                #VideoGamesRecords\CoreBundle\Message\Player\UpdatePlayerGroupRank: sync
                #VideoGamesRecords\CoreBundle\Message\Player\UpdatePlayerGameRank: sync
                #VideoGamesRecords\CoreBundle\Message\Player\UpdatePlayerSerieRank: sync
                #VideoGamesRecords\CoreBundle\Message\Player\UpdatePlayerPlatformRank: sync
                #VideoGamesRecords\CoreBundle\Message\Player\UpdatePlayerData: sync
                #VideoGamesRecords\CoreBundle\Message\Player\UpdatePlayerRank: sync
                #VideoGamesRecords\CoreBundle\Message\Team\UpdateTeamChartRank: sync
                #VideoGamesRecords\CoreBundle\Message\Team\UpdateTeamGroupRank: sync
                #VideoGamesRecords\CoreBundle\Message\Team\UpdateTeamGameRank: sync
                #VideoGamesRecords\CoreBundle\Message\Team\UpdateTeamSerieRank: sync
                #VideoGamesRecords\CoreBundle\Message\Team\UpdateTeamData: sync
                #VideoGamesRecords\CoreBundle\Message\Team\UpdateTeamRank: sync


when@test:
   framework:
       messenger:
           transports:
               # replace with your transport name here (e.g., my_transport: 'in-memory://')
               # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
               async: 'in-memory://'
