monolog:
  channels:
    - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
  monolog:
    handlers:
      main:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: debug
        channels: [ "!event", "!doctrine", "!deprecation" ]
        max_files: 5
      console:
        type: console
        process_psr_3_messages: false
        channels: [ "!event", "!doctrine", "!console", "!deprecation" ]
      doctrine:
        type: stream
        path: "%kernel.logs_dir%/doctrine.log"
        channels: [ doctrine ]
      deprecation:
        type: stream
        path: "%kernel.logs_dir%/deprecation.log"
        channels: [ deprecation ]

when@staging:
  monolog:
    handlers:
      main:
        type: fingers_crossed
        action_level: error
        handler: stream_handler
        excluded_http_codes: [ 404, 405 ]
        channels: [ "!event", "!deprecation" ]
        buffer_size: 50
      stream_handler:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: debug
      console:
        type: console
        process_psr_3_messages: false
        channels: [ "!event", "!doctrine", "!deprecation" ]


when@test:
  monolog:
    handlers:
      main:
        type: fingers_crossed
        action_level: error
        handler: nested
        excluded_http_codes: [ 404, 405 ]
        channels: [ "!event" ]
      nested:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: debug

when@prod:
  monolog:
    handlers:
      main:
        type: fingers_crossed
        action_level: error
        handler: stream_handler
        excluded_http_codes: [ 404, 405 ]
        channels: [ "!event", "!deprecation" ]
        buffer_size: 50
      stream_handler:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: debug
      console:
        type: console
        process_psr_3_messages: false
        channels: [ "!event", "!doctrine", "!deprecation" ]
